Feature/docker compose
car-parking-tracking/Parking.server pull request #20
Opened 2023-08-12 13:24 UTC by creamsandwch

docker-compose для локального разворачивания. nginx + gunicorn.

2023-08-12 16:25 UTC, ArtyKurkin approved these changes

2023-08-12 21:59 UTC, mxstrv requested changes

2023-08-12 21:59 UTC, mxstrv commented on parking_backend/settings.py
Надо в DATABASES драйвер для mysql добавить + mysqlclient в requirements

2023-08-13 18:49 UTC, LevAndreevS approved these changes

2023-08-14 10:25 UTC, mxstrv approved these changes

2023-08-14 12:24 UTC, merged